spring.application.name=ms-listaEspera
spring.datasource.url=jdbc:mysql://localhost:3306/db_listas_espera
spring.datasource.username=root
spring.datasource.password=cami1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8082